// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB47GkEhKLOGLz7UX-d_SSjGHDTT1sN5rw',
    appId: '1:592777939435:web:014d6b1532242e7ca931ae',
    messagingSenderId: '592777939435',
    projectId: 'fluttergabrielprojetocriar',
    authDomain: 'fluttergabrielprojetocriar.firebaseapp.com',
    storageBucket: 'fluttergabrielprojetocriar.firebasestorage.app',
    measurementId: 'G-BTMJSTHV12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9B6MCVTIB7TgIZMN6dDtiJCua5z1r5W4',
    appId: '1:592777939435:android:64c9bf1fe2cc4f49a931ae',
    messagingSenderId: '592777939435',
    projectId: 'fluttergabrielprojetocriar',
    storageBucket: 'fluttergabrielprojetocriar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx-VbEI19fNRFux7esPwPR_gK2YYgIzRU',
    appId: '1:592777939435:ios:31a4e0281afe1e0ca931ae',
    messagingSenderId: '592777939435',
    projectId: 'fluttergabrielprojetocriar',
    storageBucket: 'fluttergabrielprojetocriar.firebasestorage.app',
    iosBundleId: 'com.example.flutterLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx-VbEI19fNRFux7esPwPR_gK2YYgIzRU',
    appId: '1:592777939435:ios:31a4e0281afe1e0ca931ae',
    messagingSenderId: '592777939435',
    projectId: 'fluttergabrielprojetocriar',
    storageBucket: 'fluttergabrielprojetocriar.firebasestorage.app',
    iosBundleId: 'com.example.flutterLayout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB47GkEhKLOGLz7UX-d_SSjGHDTT1sN5rw',
    appId: '1:592777939435:web:2c2237844103a2c4a931ae',
    messagingSenderId: '592777939435',
    projectId: 'fluttergabrielprojetocriar',
    authDomain: 'fluttergabrielprojetocriar.firebaseapp.com',
    storageBucket: 'fluttergabrielprojetocriar.firebasestorage.app',
    measurementId: 'G-7GZYYT2TRQ',
  );
}
